### ISSUE TITLE
install Groundseg without relying on MEGACORP

### ISSUE THREAD

**Issue by chaserene** [Native-Planet/GroundSeg#569]
the current installer script, in [one way](https://github.com/Native-Planet/GroundSeg/blob/v1.4.3/release/standard_install.sh#L21) or [another](https://github.com/Native-Planet/GroundSeg/blob/v1.4.3/release/standard_install.sh#L25), less direct [way](https://archive.ph/29CHv#selection-9.14203-9.14267), requires adding software sources to the operating system that are managed by MEGACORP [1] (Docker Inc).

that's bad because not using the respective GNU/Linux distribution's Docker packages increases the software supply chain risks. after this, each time people update their packages, they have to trust not only the maintainers of their operating system, but also MEGACORP, with not taking over their computer. the attack surface is further increased by fact that the Groundseg installation script downloads MEGACORP's [installation script](https://get.docker.com/), the content of which can change anytime, outside Native Planet's control.

hell, MEGACORP can't even answer a simple "yes" or "no" to ["Is Docker still free and open source?"](https://opensource.stackexchange.com/a/5458), and feeds us [word salad](https://www.docker.com/community/open-source/) like "Docker *collaborates with the open source ecosystem* through an array of projects".

I want to run Groundseg without compromising the computer it runs on.

I tried to do that on a Debian 12 by  installing packages that I infer from the install scripts to be required and have a match in the Debian stable repo (`sudo apt install network-manager avahi-daemon docker.io containerd docker-compose runc`). then I ran [groundseg_install.sh](https://github.com/Native-Planet/GroundSeg/blob/v1.4.3/release/groundseg_install.sh). it seemed to have finished without an error and `groundseg.service` is running, but there's nothing at http://$HOSTNAME.[local|localdomain], and my log file in `/opt/nativeplanet/groundseg/logs` repeats three lines:

````
Updater: Checking internet access
Updater: Check internet access error: [Errno 111] Connection refused
Config: No internet access, checking again in 15 seconds
````

can you please offer a way to make Groundseg work strictly with packages from Debian's repos (including Backports and Fast Track)?

on a broader time scale, can you create solutions for other major GNU/Linux distributions too and make that the default, so people who take the effort to run their Urbit on hardware they control will also be in control of the software?

thank you for your work so far in making Urbit users sovereign.

---
[1] https://urbit.org/overview

**Comment by yapishu** [comment]
Hi @chaserene , GroundSeg's updater does not rely on the Docker daemon, it is a Python binary compiled with [Nuitka](https://nuitka.net/) that uses the typical http libraries to check a remote version server for updates. If it's unable to make a connection, I would make sure there isn't something else going on with your host.

**Comment by yapishu** [comment]
@chaserene I believe it ought to, GSv1.x uses the Docker REST API rather than the SDK so it and doesn't do anything exotic so it shouldn't be bound to any particular version; the error you're seeing is the result of the connection checker in the binary:

https://github.com/Native-Planet/GroundSeg/blob/master/api/utils.py#L87

It's trying to contact 1.1.1.1:53 and failing

**Comment by yapishu** [comment]
Hi @chaserene , this is one of the reasons we recommend a dedicated device for GS. GSv2 uses the Golang Docker SDK and requires a minimum API version, so we opted for silent upgrade, since most GS devices are the boxes we sell. GS runs as root and requires a minimum amount of environment homogeneity (Docker >1.43 with v2, systemd) in order to function. Sorry if that's inconvenient for you, but if you'd like to extend it to work with e.g Podman we are happy to review a PR.

With regards to the broken script -- unfortunately you caught us in a short window where the install script pointed at a non-existent tag, though it sounds like you managed to figure out the scheme.

**Comment by nallux-dozryl** [comment]
@chaserene having podman support would be ideal. #624
